
# Site settings
title: Xiaodong Wang 
name: Xiaodong Wang
subtitle: Associate  Professor
email: xdwangjsj@xmut.edu.cn
description: >
  Associate Professor 
baseurl: ""
url: "https://x-d-wang.github.io/"
github_username:  x-d-wang
disqus_baseurl: "https://x-d-wang.github.io/"
disqus_shortname: https-xdwang-github-io
permalink: :title
google-site-verification: ""

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Xiaodong Wang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: Google Scholar
    icon: github
    username: xdwang
    url: https://scholar.google.com/citations?user=PmBb50kAAAAJ&hl=zh-CN
    desc: Following me at scholar 
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Xiaodong Wang
    url: https://linkedin.com/xdwang
    desc: Connect with me on LinkedIn
    share: true

theme: jekyll-theme-minimal
